stages:
  - build
  - deploy

build-npm:
  stage: build
  image: node:18.20.1
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - .output/

deploy-output:
  stage: deploy
  dependencies:
    - build-npm
  image: alpine:latest
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
    - mkdir ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - ls
    - scp -r .output $SSH_USER@$SSH_HOST:~/learn-github-ci
