stages:
  - build
  - deploy

build-npm:
  stage: build
  image: node:18.20.1
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - .output/

deploy-output:
  stage: deploy
  image: alpine:latest
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
  script:
    - ls
    - ssh $SSH_USER@$SSH_HOST "echo 'Welcome!!!' > welcome.txt"
